<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/Pandas_Class5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [ ]:
import pandas as pd

In [ ]:
data = {
    'Product' : ['Pen','Notbook','Pencil','Marker','Eraser','Sharpener'],
    'Price' : [10,50,5,30,8,12],
    'Stock' : [100,60,200,80,150,120],
    'Rating' : [4.5,4.7,4.2,4.8,4.3,4.4]
}

df = pd.DataFrame(data)
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1    Notbook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [ ]:
# 1 sort by single  column ---> Price, ascending
df.sort_values(by='Price')

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1    Notbook     50     60     4.7

In [ ]:
# 2 sort by a single column  --> Rating,descending
df.sort_values(by='Rating',ascending=False)

     Product  Price  Stock  Rating
3     Marker     30     80     4.8
1    Notbook     50     60     4.7
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [ ]:
# sort by multiple columns --> price and stock
df.sort_values(by=['Price','Stock'])

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1    Notbook     50     60     4.7

In [ ]:
# sort index
# df.sort_index()

df.sort_index(ascending=False)

     Product  Price  Stock  Rating
5  Sharpener     12    120     4.4
4     Eraser      8    150     4.3
3     Marker     30     80     4.8
2     Pencil      5    200     4.2
1    Notbook     50     60     4.7
0        Pen     10    100     4.5

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [ ]:
print(df)

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1    Notbook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [ ]:
# mean of numeric column only
df.mean(numeric_only= True)

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [ ]:
# median of numeric column only
df.median(numeric_only= True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [ ]:
# mode of numeric column only
df.mode()

     Product  Price  Stock  Rating
0     Eraser      5     60     4.2
1     Marker      8     80     4.3
2    Notbook     10    100     4.4
3        Pen     12    120     4.5
4     Pencil     30    150     4.7
5  Sharpener     50    200     4.8

In [ ]:
# stenderd deveation
df.std(numeric_only= True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [ ]:
# discription --> complete ststical values of columns
df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [ ]:
# 1 count how many times value appears
df['Product'].value_counts()

Product
Pen          1
Notbook      1
Pencil       1
Marker       1
Eraser       1
Sharpener    1
Name: count, dtype: int64

In [ ]:
# show percentage instead of counts.
df['Product'].value_counts(normalize=True)

Product
Pen          0.166667
Notbook      0.166667
Pencil       0.166667
Marker       0.166667
Eraser       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

In [ ]:
# count value of column rating
df['Rating'].value_counts()

Rating
4.5    1
4.7    1
4.2    1
4.8    1
4.3    1
4.4    1
Name: count, dtype: int64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [ ]:
# correlation between all numeric column
df.corr(numeric_only= True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

In [ ]:
# -ve coveriance ---> one increases 2nd decreses
# +ve coveriance ---> one increases other incresing

# covereance between all numeric column
df.cov(numeric_only=True)

             Price        Stock     Rating
Price   305.766667  -713.666667   3.323333
Stock  -713.666667  2576.666667 -10.833333
Rating    3.323333   -10.833333   0.053667

In [ ]:
# correlation between two column
df['Price'].corr(df['Stock'])

np.float64(-0.8040280933316356)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [ ]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height

# 2. Sort the data by Score (descending)
# Write your code here

# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

# 4. Use value_counts on Name or any categorical column
# Write your code here

# 5. Compute corr() and cov() for all numeric columns
# Write your code here

In [ ]:
# 1. Build a DataFrame with columns: Name, Age, Score, Height
df = pd.DataFrame({
    'Name' : ['John','Jane','Jack','Jill','Joe'],
    'Age' : [20,21,22,23,24],
    'Score' : [80,90,70,60,50],
    'Height' : [170,165,180,175,160]
})
df

   Name  Age  Score  Height
0  John   20     80     170
1  Jane   21     90     165
2  Jack   22     70     180
3  Jill   23     60     175
4   Joe   24     50     160

In [ ]:
#  2. Sort the data by Score (descending)
df['Score'].sort_values()

4    50
3    60
2    70
0    80
1    90
Name: Score, dtype: int64

In [ ]:
#  3. Get mean, median, mode, and std of numeric columns

# 1. mean
print(df.mean(numeric_only= True))

# 2. median
print(df.median(numeric_only = True))

# 3. mode
print(df.mode())

# 4. std
print(df.std(numeric_only = True))

Age        22.0
Score      70.0
Height    170.0
dtype: float64
Age        22.0
Score      70.0
Height    170.0
dtype: float64
   Name  Age  Score  Height
0  Jack   20     50     160
1  Jane   21     60     165
2  Jill   22     70     170
3   Joe   23     80     175
4  John   24     90     180
Age        1.581139
Score     15.811388
Height     7.905694
dtype: float64

In [ ]:
# 4. Use value_counts on Name or any categorical column
df['Name'].value_counts()

Name
John    1
Jane    1
Jack    1
Jill    1
Joe     1
Name: count, dtype: int64

In [ ]:
#  5. Compute corr() and cov() for all numeric columns
df.corr(numeric_only = True)

        Age  Score  Height
Age     1.0   -0.9    -0.2
Score  -0.9    1.0     0.1
Height -0.2    0.1     1.0

In [ ]:
df.cov(numeric_only = True)

         Age  Score  Height
Age      2.5  -22.5    -2.5
Score  -22.5  250.0    12.5
Height  -2.5   12.5    62.5

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.