<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/pandas_class6_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 6 Assignment

## Level: Basic to Intermediate

### Instructions
- Solve all questions using Pandas.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display Unique Values

## Problem Statement
Create a DataFrame with a City column and display all unique cities.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
['Bhopal' 'Indore' 'Delhi']
```

In [2]:
import pandas as pd

In [3]:
# Write your code here
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
df = pd.DataFrame(City, columns=['City'])
df['City'].unique()

array(['Bhopal', 'Indore', 'Delhi'], dtype=object)


# Q2. Count Unique Values

## Problem Statement
Find the number of unique cities in a DataFrame.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
3
```

In [5]:
# Write your code here
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
df = pd.DataFrame(City,columns=['City'])
df['City'].nunique()

3


# Q3. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City = ["Bhopal", "Indore", "Bhopal", "Delhi"]
```

## Sample Output
```python
Bhopal    2
Indore    1
Delhi     1
```

In [7]:
# Write your code here
df = pd.DataFrame({
    'City' : ['Bhopal','Indore','Bhopal','Delhi']
})

df['City'].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q4. Group By City

## Problem Statement
Find average marks city-wise using groupby().

## Sample Input
```python
City   Marks
Bhopal 80
Bhopal 90
Delhi  70
```

## Sample Output
```python
Bhopal 85
Delhi  70
```

In [11]:
df = pd.DataFrame({
    'City' : ['Bhopal','Bhopal','Delhi'],
    'Marks' : [80,90,70]
})
# df.groupby('City')['Marks'].mean()
df.groupby('City').mean()

        Marks
City
Bhopal   85.0
Delhi    70.0

In [ ]:
# Write your code here


# Q5. Sort Values

## Problem Statement
Sort students by Marks in ascending order.

## Sample Output
```python
Sorted DataFrame
```

In [19]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Amit','Ayush',"Ajay","Jay"],
    'Marks' : [70,80,90,100],
    'Age' : [20,21,22,23]

})

df.sort_values('Marks')

    Name  Marks  Age
0   Amit     70   20
1  Ayush     80   21
2   Ajay     90   22
3    Jay    100   23


# Q6. Sort Values Descending

## Problem Statement
Sort students by Marks in descending order.

## Sample Output
```python
Sorted DataFrame
```

In [20]:
# Write your code here
df.sort_values('Marks',ascending=False)

    Name  Marks  Age
3    Jay    100   23
2   Ajay     90   22
1  Ayush     80   21
0   Amit     70   20


# Q7. Filter Records

## Problem Statement
Display students having marks greater than 75.

## Sample Output
```python
Filtered rows
```

In [21]:
# Write your code here
df[df['Marks']>75]

    Name  Marks  Age
1  Ayush     80   21
2   Ajay     90   22
3    Jay    100   23


# Q8. Multiple Conditions

## Problem Statement
Display students whose marks are greater than 70 and age is greater than 20.

## Sample Output
```python
Filtered rows
```

In [22]:
# Write your code here
df[(df['Marks']>70) & (df['Age']>20)]

    Name  Marks  Age
1  Ayush     80   21
2   Ajay     90   22
3    Jay    100   23


# Q9. Group By Department

## Problem Statement
Create Employee and Department data and find total salary department-wise.

## Sample Output
```python
HR       50000
IT      120000
```

In [23]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Amit','Ayush',"Ajay","Jay"],
    'Age' : [20,21,22,23],
    'Department' : ['HR','IT','HR','IT'],
    'Salary' : [10000,20000,30000,40000]
})

df.groupby('Department')['Salary'].sum()

Department
HR    40000
IT    60000
Name: Salary, dtype: int64


# Q10. Complete Practice Question

## Problem Statement
Create a DataFrame containing:
- Name
- Age
- City
- Marks

Perform:
1. Show unique cities
2. Count city frequency
3. Filter marks > 80
4. Sort by marks

## Sample Output
```python
Required Results
```

In [24]:
# Write your code here
df = pd.DataFrame({
    'Name': ['Amit', 'Ayush', 'Ajay', 'Jay'],
    'Age': [20, 21, 22, 23],
    'City': ['Bhopal', 'Indore', 'Bhopal', 'Delhi'],
    'Marks': [80, 90, 70, 100]
})
print(df)

df

    Name  Age    City  Marks
0   Amit   20  Bhopal     80
1  Ayush   21  Indore     90
2   Ajay   22  Bhopal     70
3    Jay   23   Delhi    100

In [26]:
# 1. Show unique cities
df['City'].unique()

array(['Bhopal', 'Indore', 'Delhi'], dtype=object)

In [27]:
# 2. Count city frequency
df['City'].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64

In [30]:
# 3. Filter marks > 80
df[df['Marks']>80]

    Name  Age    City  Marks
1  Ayush   21  Indore     90
3    Jay   23   Delhi    100

In [31]:
# 4. Sort by marks
df.sort_values('Marks')

    Name  Age    City  Marks
2   Ajay   22  Bhopal     70
0   Amit   20  Bhopal     80
1  Ayush   21  Indore     90
3    Jay   23   Delhi    100