<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd

In [ ]:
b = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age': [25, 30, 35, 40, 22],
    'score' : [85, 90, 95, 100, 92]
})

print(b)

      name  age  score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

In [ ]:
# 1. select single column
b[b['age'] > 27]

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100

In [ ]:
# select single column score 85
b[b['score']>85]

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

In [ ]:
# Multiple condition  (And) : age> 27 AND  score > 85
b[(b['age']>27) & (b['score']>85)]

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100

In [ ]:
#  multiple condition (OR)  age > 30 or score > 90

b[(b['age']>30) | (b['score']>90)]

      name  age  score
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

In [ ]:
# NOT (~)
# small age in 30
b[~(b['age']>30)]

    name  age  score
0  Alice   25     85
1    Bob   30     90
4    Eve   22     92

In [ ]:
# 6. age > 22 & score >80
b[(b['age']>22) & (b['score']>80)]

      name  age  score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40    100

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
# 1. age > 25 AND Score >85
b[(b['age']>25) & (b['score']>85)]

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100

In [ ]:
# 2. age < 35 or score >= 90
b[(b['age']>35) | (b['score']>=90)]

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

In [ ]:
# 3. age between 25 and 35
b[(b['age']>=25) & (b['age']<=35)]

      name  age  score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
#  simple qurey : age > 25
print(b.query('age>25'))

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100

In [ ]:
# multiple condition using qurey : Age < 35 and score >=85
print(b.query("age <35 and score>=85"))

    name  age  score
0  Alice   25     85
1    Bob   30     90
4    Eve   22     92

In [ ]:
# multiple condition using qurey : Age >= 30 and score >=90
print(b.query("age>=30 and score>=90"))

      name  age  score
1      Bob   30     90
2  Charlie   35     95
3    David   40    100

In [ ]:
# Theshold --> @
score = 90
b.query('score > @score')

      name  age  score
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
print(b)

      name  age  score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

In [ ]:
# 1. convert name in lower case
b['name'].str.lower()

0      alice
1        bob
2    charlie
3      david
4        eve
Name: name, dtype: object

In [ ]:
# 1. convert name in upper case
b['name'].str.upper()

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4        EVE
Name: name, dtype: object

In [ ]:
# Title() -> capitilize firest letter of all the words
b['name'].str.title() # example laxit dange -> Laxit Dange

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: object

In [ ]:
# replace a substring('OldString,'NewString)
b['name'].str.replace('Alice','Laxit')

0      Laxit
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: object

In [ ]:
# check if name column contains the letter 'a'
b[b['name'].str.contains('a')]

      name  age  score
2  Charlie   35     95
3    David   40    100

In [ ]:
# .startwith('Letter') -> letter with start A
b[b['name'].str.startswith('A')]

    name  age  score
0  Alice   25     85

In [ ]:
# .endswith('letter') -> letter with end with e
b[b['name'].str.endswith('e')]

      name  age  score
0    Alice   25     85
2  Charlie   35     95
4      Eve   22     92

In [ ]:
print(b)

      name  age  score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40    100
4      Eve   22     92

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

In [ ]:
# 1. Build a DataFrame with columns: Name, Age, City, Score
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 22],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata'],
    'Score': [85, 90, 95, 100, 92]
})

print(df)

      Name  Age       City  Score
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     90
2  Charlie   35  Bangalore     95
3    David   40    Chennai    100
4      Eve   22    Kolkata     92

In [ ]:
# . Use boolean indexing to select rows where Age > 25
df[df['Age']>25]

      Name  Age       City  Score
1      Bob   30     Mumbai     90
2  Charlie   35  Bangalore     95
3    David   40    Chennai    100

In [ ]:
# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# df[(df['City']=='Delhi') | (df['City'] == 'Mumbai')]

# using qurey by
df.query("City == 'Delhi' or City == 'Mumbai'")

    Name  Age    City  Score
0  Alice   25   Delhi     85
1    Bob   30  Mumbai     90

In [ ]:
# 4. Use query() to find rows with Score >= 85 and Age < 35
df.query("Score >= 85 and Age < 25")

  Name  Age     City  Score
4  Eve   22  Kolkata     92

In [ ]:
# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
df['City'] = df['City'].str.lower()

df['City'] = df['City'].str.replace('delhi','New Delhi')

print(df)

      Name  Age       City  Score
0    Alice   25  New Delhi     85
1      Bob   30     mumbai     90
2  Charlie   35  bangalore     95
3    David   40    chennai    100
4      Eve   22    kolkata     92

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.