<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/pandas_class4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 4 Assignment


# Q1. Select Single Column

## Problem Statement
Create a DataFrame and display only the Name column.

## Sample Input
```python
Name, Age
```

## Sample Output
```python
Only Name column
```

In [1]:
import pandas as pd

In [2]:
# Write your code here
df = pd.DataFrame({

    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]

})
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [3]:
# display Name conumn
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


# Q2. Select Multiple Columns

## Problem Statement
Display Name and Marks columns from a DataFrame.

## Sample Input
```python
Name, Marks
```

## Sample Output
```python
Selected columns
```

In [5]:
# Write your code here
df = pd.DataFrame({

    'Name': ['Alice', 'Bob', 'Charlie'],
    'Marks': [85, 92, 78],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']

})
df

      Name  Marks  Age      City
0    Alice     85   25  New York
1      Bob     92   30    London
2  Charlie     78   35     Paris

In [8]:
df[['Name','Marks']]

      Name  Marks
0    Alice     85
1      Bob     92
2  Charlie     78


# Q3. Filter Students

## Problem Statement
Display students with Marks greater than 80.

## Sample Input
```python
Marks > 80
```

## Sample Output
```python
Filtered rows
```

In [10]:
# Write your code here
df[df['Marks']>80]

    Name  Marks  Age      City
0  Alice     85   25  New York
1    Bob     92   30    London


# Q4. Filter by City

## Problem Statement
Display students belonging to Bhopal.

## Sample Input
```python
City = Bhopal
```

## Sample Output
```python
Matching rows
```

In [11]:
# Write your code here
df[df['City'] == 'Bhopal']

Empty DataFrame
Columns: [Name, Marks, Age, City]
Index: []


# Q5. Find Maximum Marks

## Problem Statement
Find the highest marks from a DataFrame.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Highest value
```

In [12]:
# Write your code here
df['Marks'].max()

92


# Q6. Find Minimum Age

## Problem Statement
Find the minimum age.

## Sample Input
```python
Age column
```

## Sample Output
```python
Minimum age
```

In [13]:
# Write your code here
df['Age'].min()

25


# Q7. Sort Data

## Problem Statement
Sort students by Marks.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Sorted DataFrame
```

In [14]:
# Write your code here
df.sort_values(by='Marks')

      Name  Marks  Age      City
2  Charlie     78   35     Paris
0    Alice     85   25  New York
1      Bob     92   30    London


# Q8. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City column
```

## Sample Output
```python
Frequency count
```

In [15]:
# Write your code here

df['City'].value_counts()

City
New York    1
London      1
Paris       1
Name: count, dtype: int64


# Q9. Group By City

## Problem Statement
Find average marks city-wise.

## Sample Input
```python
City and Marks
```

## Sample Output
```python
Grouped result
```

In [16]:
# Write your code here
df.groupby('City')['Marks'].mean()

City
London      92.0
New York    85.0
Paris       78.0
Name: Marks, dtype: float64


# Q10. Multiple Conditions

## Problem Statement
Display students with Marks > 70 and Age > 20.

## Sample Input
```python
Marks and Age
```

## Sample Output
```python
Filtered rows
```

In [19]:
# Write your code here
df.query('Marks > 70 and Age > 20')

      Name  Marks  Age      City
0    Alice     85   25  New York
1      Bob     92   30    London
2  Charlie     78   35     Paris