<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/Pandas_Class5_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Class 5 Assignment

## Topics
- sort_values()
- mean()
- median()
- mode()
- value_counts()
- corr()
- cov()

Difficulty: Easy to Moderate

## Q1. Sort Age in Ascending Order

Input:
Age = [25, 18, 30, 22]

Output:
18
22
25
30

In [1]:
# Write your code here
Age = [25, 18, 30, 22]
Age.sort()
print(Age)

[18, 22, 25, 30]

## Q2. Sort Marks in Descending Order

Input:
Marks = [70, 95, 80, 60]

Output:
95
80
70
60

In [2]:
# Write your code here
Marks = [70,95,80,60]
Marks.sort(reverse = True)
Marks

[95, 80, 70, 60]

## Q3. Find Mean Age

Input:
Age = [20, 25, 30, 25]

Output:
25.0

In [5]:
# Write your code here
Age = [20,25,30,25]
sum(Age)/len(Age)

25.0

## Q4. Find Median Marks

Input:
Marks = [50, 60, 70, 80, 90]

Output:
70

In [6]:
# Write your code here
import pandas as pd
Marks = [50,60,70,80,90]
df = pd.DataFrame(Marks)
df.median()

0    70.0
dtype: float64

## Q5. Find Mode

Input:
Age = [20, 25, 25, 30, 25]

Output:
25

In [7]:
# Write your code here
Age = [20,25,25,30,25]
df = pd.DataFrame(Age)
df.mode()

    0
0  25

## Q6. Find Maximum Score

Input:
Score = [78, 90, 67, 88]

Output:
90

In [8]:
# Write your code here
score = [78,90,67,88]
df = pd.DataFrame(score)
df.max()

0    90
dtype: int64

## Q7. Find Minimum Score

Input:
Score = [78, 90, 67, 88]

Output:
67

In [9]:
# Write your code here
score = [78,90,67,88]
df = pd.DataFrame(score)
df.min()

0    67
dtype: int64

## Q8. Count City Frequency

Input:
City = ['Bhopal','Indore','Bhopal','Jabalpur']

Output:
Bhopal      2
Indore      1
Jabalpur    1

In [12]:
# Write your code here
city = ['Bhopal','Indore','Bhopal','jabalpur']
df = pd.DataFrame(city)

df.value_counts()

0
Bhopal      2
Indore      1
jabalpur    1
Name: count, dtype: int64

## Q9. Find Percentage Frequency

Input:
City = ['A','A','B','C']

Output:
A = 50%
B = 25%
C = 25%

In [14]:
# Write your code here
City = ['A','A','B','C']
df = pd.DataFrame(City)
df.value_counts(normalize=True)*100

0
A    50.0
B    25.0
C    25.0
Name: proportion, dtype: float64

## Q10. Sort DataFrame by Salary

Input:
Name   Salary
Aman   30000
Raj    50000
Riya   40000

Output:
Raj
Riya
Aman

In [15]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Aman' , 'Raj' , 'Riya'],
    'Salary' : [30000,50000,40000],
})

df.sort_values('Salary')

   Name  Salary
0  Aman   30000
2  Riya   40000
1   Raj   50000

## Q11. Find Correlation

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
1.0

In [16]:
# Write your code here
df = pd.DataFrame({
    "Math" : [10,20,30,40],
    "Science" : [15,25,35,45]
})

df.corr()

         Math  Science
Math      1.0      1.0
Science   1.0      1.0

## Q12. Find Covariance

Input:
Math = [10,20,30,40]
Science = [15,25,35,45]

Output:
166.67 (approx)

In [17]:
# Write your code here
df = pd.DataFrame({
    "Math" : [10,20,30,40],
    "Science" : [15,25,35,45]
})

df.cov()

               Math     Science
Math     166.666667  166.666667
Science  166.666667  166.666667

## Q13. Sort by Two Columns

Input:
Sort by City and then Age

Output:
Sorted DataFrame

In [19]:
# Write your code here
df = pd.DataFrame({
    'Name' : ['Laxit','Amit','Yash','Rohit','Priya'],
    'Age' : [20,21,22,23,24],
    'City' : ['Delhi','Mumbai','Delhi','Mumbai','Delhi']
})

df.sort_values(by=['City','Age'])

    Name  Age    City
0  Laxit   20   Delhi
2   Yash   22   Delhi
4  Priya   24   Delhi
1   Amit   21  Mumbai
3  Rohit   23  Mumbai

## Q14. Student Statistics

Input:
Marks = [60,70,80,90]

Output:
Mean = 75
Median = 75
Max = 90
Min = 60

In [20]:
# Write your code here
df = pd.DataFrame({
    'Marks' : [60,70,80,90]
})
print("Mean = ",df.mean())
print("Median = ",df.median())
print("Max = ",df.max())
print("Min = ",df.min())

Mean =  Marks    75.0
dtype: float64
Median =  Marks    75.0
dtype: float64
Max =  Marks    90
dtype: int64
Min =  Marks    60
dtype: int64

## Q15. Mini Practice

Create a DataFrame with:
Name, Age, Score, Height

Tasks:
1. Sort by Score (Descending)
2. Find Mean Age
3. Find Median Height
4. Show Score Frequency

In [22]:
# Write your code here
df = pd.DataFrame({
    'Nmae' : ['Jay','Veru','Amit','Yeas','Ayush'],
    'Age' : [20,21,22,23,24],
    'Score' : [90,80,70,60,50],
    'Height' : [170,175,180,185,188]
})
print(df)

    Nmae  Age  Score  Height
0    Jay   20     90     170
1   Veru   21     80     175
2   Amit   22     70     180
3   Yeas   23     60     185
4  Ayush   24     50     188

In [23]:
# 1. Sort by Score (Descending)
df['Score'].sort_values(ascending=False)

0    90
1    80
2    70
3    60
4    50
Name: Score, dtype: int64

In [25]:
# 2. Find Mean Age
print(df['Age'].mean())

22.0

In [26]:
# 3. Find Median Height
print(df['Height'].median())

180.0

In [27]:
# 4. Show Score Frequency
df['Score'].value_counts()

Score
90    1
80    1
70    1
60    1
50    1
Name: count, dtype: int64