<a href="https://colab.research.google.com/github/laxitdange28-tech/Pandas-notes/blob/main/Pandas_class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [ ]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)
print(b)

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [ ]:
#1.  .isna()
print(b.isna())

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [ ]:
#2. .isnull
print(b.isnull())

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [ ]:
print(b.isnull().sum()) # column wise null vallues count

Name     0
Age      2
City     1
Score    1
dtype: int64

In [ ]:
# 3. dropna()
b.dropna() # Remove all null value rows

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
3  David  40.0  Bangalore   88.0

In [ ]:
print(b)

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [ ]:
# 4. fillna numaric data ko mean,median , object -> mode

b['Age'].fillna(b['Age'].mean(), inplace=True)
print(b)

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000       None    NaN
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

/tmp/ipykernel_5437/3710195584.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Age'].fillna(b['Age'].mean(), inplace=True)

In [ ]:
b['Score'].fillna(0,inplace=True)
print(b)

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000       None    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

/tmp/ipykernel_5437/541776496.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Score'].fillna(0,inplace=True)

In [ ]:
b['City'].fillna("Unknow",inplace=True)
print(b)

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000     Unknow    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

/tmp/ipykernel_5437/2248860648.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['City'].fillna("Unknow",inplace=True)

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [ ]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

In [ ]:
b['Age'].astype('float')

0    25.0
1    30.0
2    35.0
3    40.0
4    22.0
Name: Age, dtype: float64

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [ ]:
print(b)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
b['Name'].replace('Alice','Rohit',inplace=True)
print(b)

      Name  Age  Score
0    Rohit   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

/tmp/ipykernel_5437/115837524.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Name'].replace('Alice','Rohit',inplace=True)

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [ ]:
print(b)

      Name  Age  Score
0    Rohit   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
# Remove row
# b.drop(index=2,axis=0,inplace=True)
print(b)

      Name  Age  Score
0    Rohit   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
# Remove column
# b.drop(columns='Score',axis=1,inplace=True)
print(b)

      Name  Age  Score
0    Rohit   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)

In [ ]:
print(df)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

In [ ]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [ ]:
df.duplicated().sum() # Total duplicate row

np.int64(2)

In [ ]:
df.drop_duplicates(inplace=True)
print(df)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [ ]:

# 1. Create a messy DataFrame

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

In [ ]:
# 1. Create a messy DataFrame

import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],
    "Score": [85, None, 78, 88, 85, 91],
    "Extra": ["x", "y", "z", "x", "y", "z"]
}
print("Original messy DataFrame:")
print(df)

Original messy DataFrame:
      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    0.0     y
2  Charlie   25       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5   Unknow   30     Mumbai   91.0     z

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 128.0+ bytes

In [ ]:
# 2. Handle missing values
# Fill or drop as needed

df['Name'].fillna("Unknow",inplace=True)

df['Age'].fillna(df['Age'].mode()[0],inplace=True)

df['Score'].fillna(0,inplace = True)



print(df)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

/tmp/ipykernel_5437/3863585975.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].fillna("Unknow",inplace=True)
/tmp/ipykernel_5437/3863585975.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mode()[0],inplace=True)
/tmp/ipykernel_5437/3863585975.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score'].fillna(0,inplace = True)

In [ ]:
# 3. Change data types
# Convert Age to int, Score to float, etc.

df['Age'] = df['Age'].astype(int)
df['Score'] = df['Score'].astype(float)

print(df)

      Name  Age  Score
0    Alice   25   88.0
1      Bob   30   92.0
2  Charlie   35   79.0
5    David   40   85.0

In [ ]:
df

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    0.0     y
2  Charlie   25       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5   Unknow   30     Mumbai   91.0     z

In [ ]:
# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

df['City'].replace('Pun','Pune',inplace=True)
print(df)

      Name  Age       City  Score Extra
0    Alice   25      Delhi   85.0     x
1      Bob   30     Mumbai    0.0     y
2  Charlie   25       Pune   78.0     z
3    David   40  Bangalore   88.0     x
4    Alice   25      Delhi   85.0     y
5   Unknow   30     Mumbai   91.0     z

/tmp/ipykernel_5437/464760476.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].replace('Pun','Pune',inplace=True)

In [ ]:
# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

df.drop(columns = 'Extra',axis=1,inplace=True)
print(df)

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai    0.0
2  Charlie   25       Pune   78.0
3    David   40  Bangalore   88.0
4    Alice   25      Delhi   85.0
5   Unknow   30     Mumbai   91.0

In [ ]:
# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

df[df.duplicated()]

    Name  Age   City  Score
4  Alice   25  Delhi   85.0

In [ ]:
df.drop_duplicates(inplace=True)
print(df)

      Name  Age       City  Score
0    Alice   25      Delhi   85.0
1      Bob   30     Mumbai    0.0
2  Charlie   25       Pune   78.0
3    David   40  Bangalore   88.0
5   Unknow   30     Mumbai   91.0

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.